version : '3.3'

services:
  sqlserver:
    image: microsoft/mssql-server-linux
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pocRabbit123
    ports:
      - 1433:1433

  rabbitmq:
    image: coisa2004/rabbitmq-delay
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    container_name: rabbitmq-delay
    ports:
      - "5672:5672"
      - "15672:15672"